from pathlib import Path

BASE_DIR = Path(__file__).parent
DATA_DIR = BASE_DIR / "data"
STRUCTURES_DIR = DATA_DIR / "structures"
CHEMBL_DIR = DATA_DIR / "chembl"
ZINC_DIR = DATA_DIR / "zinc"
RESULTS_DIR = DATA_DIR / "results"

for d in [STRUCTURES_DIR, CHEMBL_DIR, ZINC_DIR, RESULTS_DIR]:
    d.mkdir(parents=True, exist_ok=True)

CASP9_PDB_ID = "2AR9"
ALPHASYN_PDB_ID = "8A9L"
CASP9_CHEMBL_ID = "CHEMBL2093868"
CHEMBL_LIMIT = 1000

DOCKING_CENTER = [14.0, 50.0, 28.0]
DOCKING_BOX_SIZE = [20, 20, 20]
DOCKING_EXHAUSTIVENESS = 32
DOCKING_N_POSES = 10
DOCKING_SCORE_CUTOFF = -7.0

CHEMBERTA_MODEL = "seyonec/ChemBERTa-zinc-base-v1"
ML_KI_CUTOFF_NM = 100.0
BATCH_SIZE = 64
EPOCHS = 10
LEARNING_RATE = 2e-5

LIPINSKI_MW_MAX = 500
LIPINSKI_LOGP_MAX = 5
LIPINSKI_HBD_MAX = 5
LIPINSKI_HBA_MAX = 10
PKCSM_API_URL = "https://biosig.lab.uq.edu.au/pkcsm/api/"

TOP_N_CANDIDATES = 20
